server {
    listen 127.0.0.1:8080;
    listen localhost:80;
    server_name alpha_server;
    client_max_bady_size 2000;

    error_page 400 /errors/400.html;
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # --- Locations ---
    location / {
        methods GET POST;
        root /var/www/alpha/html;
        autoindex on;
        index index.html;
    }

    location /upload {
        methods POST;
        root /var/www/alpha/uploads;
        upload_enable on;
        upload_store /var/www/alpha/uploads;
    }

    location /redirect {
        methods GET;
        root /var/www/alpha/html;
        return 301 http://new.alpha.com/;
    }

    location /cgi-bin {
        methods GET POST;
        root /var/www/alpha/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}