server {
    listen 127.0.0.1:8080;
	listen :;
	listen 131.232.13.15:8078;
    listen localhost:80;
    server_name multiple_listens;
    client_max_bady_size 2000;

    # --- Locations ---
    location / {
        methods GET POST;
        root /var/www/alpha/html;
        autoindex on;
        index index.html;
    }
}