server {
    listen 127.0.0.1:8080;
    listen localhost:80;
    server_name alpha_server;

    # --- Locations ---
    location / {
        methods GET POST;
        root /var/www/alpha/html;
        autoindex on;
        index index.html;
    }

    location /upload {
        methods POST;
        root /var/www/alpha/uploads;
        upload_enable on;
        upload_store /var/www/alpha/uploads;
    }

    location /redirect {
        methods GET ;
        root /var/www/alpha/html;
        return 301 http://new.alpha.com/;
    }

    location /cgi-bin {
        methods GET POST ;
        root /var/www/alpha/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    location /cgi-bin {
        methods GET POST DELETE;
        root /var/www/alpha/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}