server {
    listen 127.0.0.1:8080;
    server_name first;
    client_max_body_size 5000000;

	error_page 405 www/errors/405.html;
	error_page 500 www/errors/500.html;
    error_page 404 www/errors/404.html;

    location / {
		methods GET POST;
        root ./www;
        index index.html;
        autoindex off;
    }

    location /cgi-bin/ {
        root ./www;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
		upload_enable on;
    }

    location /uploads/ {
        root ./www;
		upload_enable on;
		upload_store ./www/uploads;
    }
}

server {
    listen 127.0.0.1:8079;
    server_name second;
    client_max_body_size 5000000;

	error_page 500 www/errors/500.html;
    error_page 404 www/errors/404.html;

    location / {
		methods GET POST;
        root ./www;
        index index.html;
        autoindex on;
    }

    location /cgi-bin {
        root ./www;
		methods GET POST;
		autoindex on;
		alias /cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
		upload_enable on;
    }

    location /uploads {
        root ./www;
		alias /uploads;
		methods GET POST DELETE;
		autoindex on;
		upload_enable on;
		upload_store ./www/uploads;
    }
}

