server {
    listen 127.0.0.1:8080;
    server_name main;
    location / { root ./www; index index.html; }
}

server {
    listen 127.0.0.1:8081;
    server_name backup;
    location / { root ./www; index index.html; }
}
