server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 5000000;

    # -------------------------
    # Default static files
    # -------------------------
    location / {
        methods GET POST;
        root ./www/evaltest;
        index index.html;
        autoindex off;
    }

    # -------------------------
    # CGI handler (Python)
    # -------------------------
    location /cgi-bin/ {
        methods GET POST;
        root ./www/evaltest;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        upload_enable on;
    }

    # -------------------------
    # Optional upload directory
    # -------------------------
    location /uploads/ {
        root ./www/evaltest;
        upload_enable on;
        upload_store ./www/evaltest/uploads;
    }
}
