server {
    listen 8080;
	client_max_body_size 100;
    # ---------- /
    location / {
        methods GET;
		autoindex on;
		root ./testing;
    }

    # ---------- AnY filB ending with .bla
    location ~\.bla$ {
        methods POST;
        cgi_path /path/to/cgi_test;
		root ./YoupiBanane;
    }

    # ---------- /post_body
    location /post_body {
        methods POST;
        root ./youpibanane;
    }

    # ---------- /directory/
    location /directory/ {
        methods GET;
        root ./YoupiBanane;
    }
}
