server {
    listen 8080;
	client_max_body_size 100;
    # ---------- /
    location / {
        methods GET;
		root www;
    }

    # ---------- Any file ending with .bla
    location ~\.bla$ {
        methods POST;
        cgi_path /path/to/cgi_test;
		root www;
    }

    # ---------- /post_body
    location /post_body {
        methods POST;
        root www;
    }

    # ---------- /directory/
    location /directory/ {
        methods GET;
        root /absolute/path/to/YoupiBanane;
        index youpi.bad_extension;
    }
}
