server {
    listen 127.0.0.1:8083;
    server_name uploader;

	location / {
		root ./www;
		methods GET POST;
		index index.html;
	}

    location /upload {
        root ./www/uploads;
        methods GET POST;
        upload_enable on;
        upload_store ./www/uploads;
    }

	location /cgi-bin/ {
        root ./www;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        upload_enable on;
        upload_store ./www/uploads;
    }
}