server {
    listen 127.0.0.1:8083;
    server_name uploader;

    location /upload {
        root ./www/uploads;
        methods POST;
        upload_enable on;
        upload_store ./www/uploads;
    }
}