server {
	listen 127.0.0.1:8089;
	client_max_body_size 1000;

	location / {
		methods GET POST;
		root ./www/YoupiBanane;
		autoindex on;
	}

	location /directory/ {
		methods GET POST;
		root ./www/YoupiBanane;
		cgi_extension .bla;
		cgi_path /www/ubuntu_cgi_tester;
		index youpi.bad_extension;
	}

	location /post_body {
		methods GET POST;
		root ./www/YoupiBanane;
	}
	
}